#Application port
server:
  port: 8888
  error:
    whitelabel:
      enabled: false

spring:

  #Database connection
  datasource:
    url: jdbc:h2:mem:practice_db
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always
    sql-script-encoding: UTF-8

  #Hibernate configuration
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false

  mvc:
    throw-exception-if-no-handler-found: true

  resources:
    add-mappings: false

logging:
  level:
    ROOT: WARN